# Generated by Django 2.0.7 on 2018-07-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
